default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: foodicted_development

test:
  <<: *default
  database: foodicted_test

production:
  <<: *default
  database: foodicted_production
  username: foodicted
  password: <%= ENV['FOODICTED_DATABASE_PASSWORD'] %>
