# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f755cc0fb35e5bcdb36f745b0f7a5a64b584e476403dc13d0b500baef62d5425cf198d5079434f6e2375fd88845bd4f60686b317653adf51bf48540253aa18f7

test:
  secret_key_base: 3a5ed4cdc4f8ce3a8787f648d64a4acfc5b93f54bc7e54d81331b20b1aea5a3bd987325bb4041964b00b8754da5c9800d3b13da1515405ec4f5ae0f79c39e345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
